sudo: false
language: node_js
node_js:
    - 8
    - 9
script:
    - npm test
    - npm run lint
addons:
  code_climate:
    repo_token: afde2ff0d8ac5bc92d7fb27c5c5d6a691095a0f3b1346c67c4f536c83cc345d3
after_success: npm run coverage
